version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/geodish
      - SECRET_KEY=geodish-dev-secret-2024
    depends_on:
      - mongodb
    networks:
      - geodish-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - geodish-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - app
    networks:
      - geodish-network

volumes:
  mongodb_data:

networks:
  geodish-network:
    driver: bridge
#note: best pratice: dont expose ports of database to the outside world, only to other services in the same network.