version: '3.8'

services:
  app:
    build: .  # ✅ Build from source like original.
    expose:
      - "5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongodb
    networks:
      - geodish-network

  mongodb:
    image: mongo:7.0
    expose:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - geodish-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - app
    networks:
      - geodish-network

volumes:
  mongodb_data:

networks:
  geodish-network:
    driver: bridge
