version: '3.8'

services:
  app:
    build: .
    # ❌ REMOVED: ports: - "5000:5000"  # No external access to Flask
    expose:
      - "5000"  # ✅ Only exposed to internal network
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/geodish
      - SECRET_KEY=geodish-dev-secret-2024
    depends_on:
      - mongodb
    networks:
      - geodish-network

  mongodb:
    image: mongo:7.0
    # ❌ REMOVED: ports: - "27017:27017"  # No external access to database.
    expose:
      - "27017"  # ✅ Only exposed to internal network
    volumes:
      - mongodb_data:/data/db
    networks:
      - geodish-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # ✅ ONLY public access point
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - app
    networks:
      - geodish-network

volumes:
  mongodb_data:

networks:
  geodish-network:
    driver: bridge
